// PAL Institute — single source of truth for rebranding
export const SITE = {
  instituteName: "PAL INSTITUTE",
  tagline: "Where Toppers Are Made",
  phone: "+91-70431-43166",
  phoneDigits: "917043143166",
  email1: "palinstituteonline@gmail.com",
  email2: "palinstituteoffline@gmail.com",
  address:
    "Shree Palace, Near Patel Society, Behind Technical School, Chhapra Road, Navsari, Gujarat, India",
  city: "Navsari",
  social: {
    instagram: "https://www.instagram.com/palinstitute/",
    youtube: "https://www.youtube.com/@PALINSTITUTE-DineshPal",
    facebook: "#",
    telegram: "#",
  },
  externalLinks: {
    onlineCourses: "https://palinstitute.akamai.net.in/",
    pathshala: "https://www.pw.live/",
  },
  admissions: {
    closingDate: "2026-06-30T23:59:59",
    batchStartAnnouncement:
      "New batch starting 1st June 2026 — Limited seats!",
    nextScholarshipTest: "15th May 2026 (Sunday)",
  },
  heroStats: [
    { label: "Selections", value: 500, suffix: "+" },
    { label: "Years", value: 10, suffix: "+" },
    { label: "Faculty", value: 50, suffix: "+" },
    { label: "Success Rate", value: 95, suffix: "%" },
  ],
  aggregateStats: [
    { label: "IIT/NIT/IIIT Selections (Lifetime)", value: 50, suffix: "+" },
    { label: "Medical Selections (Lifetime)", value: 80, suffix: "+" },
    { label: "Students above 90% in Boards", value: 95, suffix: "%" },
    { label: "Students in Top 3000 (JEE/NEET)", value: 50, suffix: "+" },
  ],
  programsDropdown: [
    "JEE (Main + Advanced)",
    "NEET (UG)",
    "Foundation (Class 8-10)",
    "Primary Foundation (Class 1-7)",
    "Board Exam Crash Course",
    "Board Batch (Class 8-10)",
    "Board Batch (Class 11-12)",
    "Dropper Batch (JEE/NEET)",
    "Scholarship Test",
  ],
  classDropdown: [
    "Class 1-7",
    "Class 8",
    "Class 9",
    "Class 10",
    "Class 11",
    "Class 12",
    "12th Pass (Dropper)",
  ],
  sources: [
    "Google",
    "Instagram",
    "YouTube",
    "Friend/Relative",
    "Newspaper",
    "Pamphlet",
    "Other",
  ],
  timings: [
    "Morning 7-9 AM",
    "Day 10 AM-12 PM",
    "Noon 2-5 PM",
    "Evening 5-9 PM",
  ],
};

export const COURSES = [
  {
    id: "jee",
    title: "JEE (Main + Advanced)",
    duration: "1 Year / 2 Year Programs",
    forWhom: "Class 11 & 12 Students",
    subjects: "Physics, Chemistry, Mathematics",
    batch: "Max 35 students",
    fee: "₹85,000/year (EMI available)",
    highlights: [
      "Daily practice tests",
      "Doubt-clearing sessions",
      "Study material included",
    ],
    accent: "navy",
    icon: "atom",
  },
  {
    id: "neet",
    title: "NEET (UG)",
    duration: "1 Year / 2 Year Programs",
    forWhom: "Class 11 & 12 Students (PCB)",
    subjects: "Physics, Chemistry, Biology",
    batch: "Max 30 students",
    fee: "₹80,000/year",
    highlights: [
      "Weekly mock tests",
      "NCERT mastery program",
      "Hospital visit exposure",
    ],
    accent: "gold",
    icon: "stethoscope",
  },
  {
    id: "foundation",
    title: "Foundation (Class 8-9-10)",
    duration: "Annual Program",
    forWhom: "Class 8, 9, 10 Students",
    subjects: "Maths, Science, English, SST",
    batch: "Max 25 students",
    fee: "₹45,000/year",
    highlights: [
      "Board exam prep + Olympiad training",
      "NTSE preparation",
    ],
    accent: "navy",
    icon: "book-open",
  },
  {
    id: "board-crash",
    title: "Board Exam Crash Course",
    duration: "3 Months (Jan-March)",
    forWhom: "Class 10 & 12 Students",
    subjects: "Full syllabus revision",
    batch: "Intensive batch",
    fee: "₹15,000",
    highlights: [
      "Complete syllabus revision",
      "30+ mock tests",
      "Previous year paper solving",
    ],
    accent: "gold",
    icon: "clock",
  },
  {
    id: "dropper",
    title: "Dropper Batch (JEE/NEET)",
    duration: "1 Year",
    forWhom: "12th Pass Students (Gap Year)",
    subjects: "Full focus — PCM/PCB",
    batch: "Small focused batch",
    fee: "₹75,000",
    highlights: [
      "Intensive daily 8-hour program",
      "Personal mentor",
      "Weekly parent updates",
    ],
    accent: "navy",
    icon: "target",
  },
  {
    id: "primary",
    title: "Primary Foundation (Class 1-7)",
    duration: "Annual Program",
    forWhom: "Class 1 to 7 Students",
    subjects: "Maths, Science, English, Logical Reasoning",
    batch: "Max 25 students",
    fee: "₹10,000 to 25,000/year",
    highlights: [
      "Strong basic concept building",
      "Activity-based learning",
      "Weekly tests & progress tracking",
      "Personal attention for every student",
    ],
    accent: "gold",
    icon: "graduation-cap",
  },
  {
    id: "board-8-10",
    title: "Board Batch (Class 8-9-10)",
    duration: "Annual Program",
    forWhom: "Class 8, 9, 10 Students (Board Focus Only)",
    subjects: "Maths, Science, English, SST",
    batch: "Max 30 students",
    fee: "₹25,000 to 35,000/year",
    highlights: [
      "Complete board exam preparation",
      "NCERT + Board pattern coverage",
      "Regular tests & revision sessions",
      "Important questions & paper practice",
    ],
    accent: "navy",
    icon: "notebook-pen",
  },
  {
    id: "board-11-12",
    title: "Board Batch (Class 11-12)",
    duration: "Annual Program",
    forWhom: "Class 11 & 12 Students — Science & Commerce",
    subjects:
      "Science: Physics, Chemistry, Maths/Biology · Commerce: Accounts, Economics, Business Studies, Maths",
    batch: "Max 30 students",
    fee: "Science ₹54,999/yr · Commerce ₹44,999/yr",
    highlights: [
      "Complete Board Prep (GSEB/CBSE)",
      "NCERT + Board pattern coverage",
      "Chapter-wise tests & final mocks",
      "Answer writing practice & paper strategy",
      "Regular doubt-solving sessions",
    ],
    accent: "gold",
    icon: "library",
  },
];

export const FACULTY = [
  { subject: "Physics", years: "18 years", specialization: "Mechanics & Electrodynamics" },
  { subject: "Chemistry", years: "15 years", specialization: "Organic Chemistry" },
  { subject: "Mathematics", years: "12 years", specialization: "Calculus & Coordinate Geometry" },
  { subject: "Biology", years: "16 years", specialization: "Human Physiology & Genetics" },
  { subject: "Maths (Foundation)", years: "10 years", specialization: "Algebra & Number Theory" },
];

export const USPS = [
  { title: "Daily Practice Tests", desc: "Timed topic-wise tests every day to build exam temperament.", icon: "clipboard-check" },
  { title: "Small Batch Size", desc: "Max 30-35 students per batch for personal attention.", icon: "users" },
  { title: "Parent App / Updates", desc: "Weekly progress reports sent to parents via WhatsApp.", icon: "message-circle" },
  { title: "Doubt Clearing Sessions", desc: "Dedicated 1-hour doubt sessions after every class.", icon: "help-circle" },
  { title: "Comprehensive Material", desc: "In-house printed modules covering the complete syllabus.", icon: "book-marked" },
  { title: "Scholarship for Toppers", desc: "Up to 100% fee waiver based on entrance test performance.", icon: "award" },
];

export const SCHOLARSHIP_SLABS = [
  { score: "90%+", waiver: "90% Fee Waiver" },
  { score: "80-89%", waiver: "50% Fee Waiver" },
  { score: "70-79%", waiver: "25% Fee Waiver" },
  { score: "60-69%", waiver: "10% Fee Waiver" },
];

export const FAQS = [
  { q: "What is the batch timing?", a: "Morning (6-10 AM), Day (10 AM-12 PM), Evening (2-5 PM) / Evening (5-9 PM)" },
  { q: "Is there a free demo class?", a: "Yes, book from our website or call us." },
  { q: "What is the fee structure?", a: "Varies by program. See Courses section or enquire." },
  { q: "Do you provide study material?", a: "Yes, comprehensive in-house material included in fee." },
  { q: "What is the batch size?", a: "Maximum 30-35 students for personal attention." },
  { q: "Is there an EMI option for fees?", a: "Yes, we offer 3/6/12 month EMI options." },
  { q: "Do you have a hostel facility?", a: "Yes, separate boys and girls hostels available." },
  { q: "What are the selection results?", a: "50+ IIT/NIT/IIIT selections, 80+ medical selections lifetime." },
  { q: "Is there a scholarship test?", a: "Yes, conducted monthly. Up to 100% fee waiver." },
  { q: "Can parents attend demo class?", a: "Absolutely, we encourage parents to observe our teaching." },
];

export const SOCIAL_PROOF = [
  { name: "Rohit", city: "Dwarka", action: "booked a demo class" },
  { name: "Priya", city: "Navsari", action: "enquired about NEET batch" },
  { name: "Aman", city: "Surat", action: "registered for scholarship test" },
  { name: "Sneha", city: "Valsad", action: "booked a demo class" },
  { name: "Vikram", city: "Bilimora", action: "enquired about JEE batch" },
  { name: "Kavya", city: "Vapi", action: "booked a demo class" },
  { name: "Harsh", city: "Gandevi", action: "enquired about Foundation" },
  { name: "Meera", city: "Chikhli", action: "registered for scholarship test" },
];
